// Generated by CoffeeScript 2.3.1
(function() {
  // Deletes all images that are memes or screenshots.
  var Script, fs, path, utils;

  fs = require("fs");

  path = require("path");

  utils = require("./utils.js");

  // Script implementation.
  Script = async function(folders) {
    var ex, file, folder, folderTags, i, j, len, len1, result, score, tags, tagsfile, toDelete;
    // Minimum score to consider.
    score = 0.8;
    // Array of files to be deleted.
    toDelete = [];
    try {
      for (i = 0, len = folders.length; i < len; i++) {
        folder = folders[i];
        folderTags = utils.getFolderTags(folder);
        for (file in folderTags) {
          tags = folderTags[file];
          try {
            if (tags.meme == null) {
              tags.meme = 0;
            }
            if (tags.screenshot == null) {
              tags.screenshot = 0;
            }
            if (parseFloat(tags.meme) > score || parseFloat(tags.screenshot) > score) {
              tagsfile = file + ".tags";
              toDelete.push(file);
              toDelete.push(tagsfile);
              console.log(`${imgfile} - meme: ${tags.meme}, screenshot: ${tags.screenshot}`);
            }
          } catch (error) {
            ex = error;
            console.error(file, ex);
          }
        }
      }
// Delete unsafe files.
      for (j = 0, len1 = toDelete.length; j < len1; j++) {
        file = toDelete[j];
        try {
          result = fs.unlinkSync(file);
          console.log(`${file} - deleted`);
        } catch (error) {
          ex = error;
          console.error(file, ex);
        }
      }
      return (await true);
    } catch (error) {
      ex = error;
      console.error(ex);
      throw ex;
    }
  };

  // Export!
  module.exports = Script;

}).call(this);
