// Generated by CoffeeScript 2.4.1
(function() {
  // Deletes all images that are very likely adult, violence, or a good mix of unsafe categories.
  var Script, fs, path, utils;

  fs = require("fs");

  path = require("path");

  utils = require("./utils.js");

  // Script implementation.
  Script = async function(folders) {
    var ex, file, folder, folderTags, i, imgTotalScore, imgfile, j, len, len1, result, singleScore, tags, toDelete, totalScore;
    // Maximum safe single / total scores to consider.
    // Anything above these values is considered unsafe.
    singleScore = 0.8;
    totalScore = 1.5;
    // Array of files to be deleted.
    toDelete = [];
    try {
      for (i = 0, len = folders.length; i < len; i++) {
        folder = folders[i];
        folderTags = utils.getFolderTags(folder);
        for (file in folderTags) {
          tags = folderTags[file];
          try {
            if (tags.adult == null) {
              tags.adult = 0;
            }
            if (tags.spoof == null) {
              tags.spoof = 0;
            }
            if (tags.medical == null) {
              tags.medical = 0;
            }
            if (tags.racy == null) {
              tags.racy = 0;
            }
            if (tags.violence == null) {
              tags.violence = 0;
            }
            imgTotalScore = tags.adult + tags.spoof + tags.medical + tags.racy + tags.violence;
            if (tags.adult > singleScore || tags.violence > singleScore || imgTotalScore > totalScore) {
              imgfile = file.substring(0, file.length - 5);
              toDelete.push(imgfile);
              toDelete.push(file);
              console.log(`  ${imgfile} marked as unsafe`);
            }
          } catch (error) {
            ex = error;
            console.error(file, ex);
          }
        }
        console.log("");
      }
// Delete unsafe files.
      for (j = 0, len1 = toDelete.length; j < len1; j++) {
        file = toDelete[j];
        try {
          result = fs.unlinkSync(file);
          console.log(`  ${file} - deleted`);
        } catch (error) {
          ex = error;
          console.error(`  ${file}`, ex);
        }
      }
      return (await true);
    } catch (error) {
      ex = error;
      console.error(ex);
      throw ex;
    }
  };

  // Export!
  module.exports = Script;

}).call(this);
