// Generated by CoffeeScript 2.3.2
(function() {
  // Deletes all images that have adult or violence.
  var Script, fs, path, utils;

  fs = require("fs");

  path = require("path");

  utils = require("./utils.js");

  // Script implementation.
  Script = async function(folders) {
    var ex, file, folder, folderTags, i, imgfile, j, len, len1, result, score, tags, toDelete;
    // Minimum score to consider.
    score = 0.001;
    // Array of files to be deleted.
    toDelete = [];
    try {
      for (i = 0, len = folders.length; i < len; i++) {
        folder = folders[i];
        folderTags = utils.getFolderTags(folder);
        for (file in folderTags) {
          tags = folderTags[file];
          try {
            if (tags.adult == null) {
              tags.adult = 0;
            }
            if (tags.violence == null) {
              tags.violence = 0;
            }
            if (parseFloat(tags.adult) > score || parseFloat(tags.violence) > score) {
              imgfile = file.substring(0, file.length - 5);
              toDelete.push(imgfile);
              toDelete.push(file);
              console.log(`  ${imgfile} - adult: ${tags.adult}, violence: ${tags.violence}`);
            } else {
              console.log(`  ${imgfile} - safe`);
            }
          } catch (error) {
            ex = error;
            console.error(file, ex);
          }
        }
        console.log("");
      }
// Delete unsafe files.
      for (j = 0, len1 = toDelete.length; j < len1; j++) {
        file = toDelete[j];
        try {
          result = fs.unlinkSync(file);
          console.log(`  ${file} - deleted`);
        } catch (error) {
          ex = error;
          console.error(`  ${file}`, ex);
        }
      }
      return (await true);
    } catch (error) {
      ex = error;
      console.error(ex);
      throw ex;
    }
  };

  // Export!
  module.exports = Script;

}).call(this);
